---
name: Internet
locale: es
type: learning
beta: false
teacher_info: "Los **clientes** se comunican a través de métodos **HTTP** con **servidores**
  y solicitan información que estos últimos pueden buscar en una **base de datos**.\n\nSi
  solamente uno de todos los actores no funcionara bien, lo más probable es que todo
  este **sistema** falle :boom:. Y eso sin contar con el soporte físico, aparatos
  y cables que tienen que estar funcionando y en condiciones. :scream: \n\n"
language: text
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 6
- 5
- 7
- 8
- 9
- 10
- 11
- 12
