---
name: Aplicaciones en Internet
locale: es
type: learning
beta: false
teacher_info: "¿Para qué sirve Internet? Para enviar correos electrónicos, para chatear,
  para navegar páginas. Cada una de estas cosas que podemos hacer es un servicio de
  internet. \n\n"
language: text
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
