---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Navegar por páginas web
  checked: false
- value: Enviar correos electrónicos (_emails_)
  checked: false
- value: Realizar videollamadas
  checked: false
- value: Chatear
  checked: false
- value: Todas las anteriores
  checked: true
name: Los usos de Internet
