---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Cliente consulta al servidor; servidor gestiona y envía datos.
  checked: true
- value: Cliente consulta al servidor; cliente gestiona y envía datos.
  checked: false
- value: Servidor consulta al cliente; cliente gestiona y envía datos.
  checked: false
- value: Servidor consulta al cliente; servidor gestiona y envía datos.
  checked: false
