---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: WAN
  checked: false
- value: LAN
  checked: false
- value: Dirección IP
  checked: false
- value: Nombre de dominio
  checked: true
name: La reina de los servicios
